/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_milton_common_demo_activity_jni_HelloJniActivity */

#ifndef _Included_com_milton_common_demo_activity_jni_HelloJniActivity
#define _Included_com_milton_common_demo_activity_jni_HelloJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_milton_common_demo_activity_jni_HelloJniActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_milton_common_demo_activity_jni_HelloJniActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
