/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_milton_jnitest_NdkJniUtils */

#ifndef _Included_com_milton_jnitest_NdkJniUtils
#define _Included_com_milton_jnitest_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_milton_jnitest_NdkJniUtils_getCLanguageString
        (JNIEnv *, jobject);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    calAAndB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_milton_jnitest_NdkJniUtils_calAAndB
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    loginServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_loginServer
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    intArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_intArray
        (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    stringArray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_stringArray
        (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    callCcode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_callCcode
        (JNIEnv *, jobject);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    callCcode2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_callCcode2
        (JNIEnv *, jobject);

/*
 * Class:     com_milton_jnitest_NdkJniUtils
 * Method:    callCcode3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_milton_jnitest_NdkJniUtils_callCcode3
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
